<?php

/**
 * Implements hook_menu().
 */
function lobbywatch_menu() {
  $items = array();

  $items['parlamentarier'] = array(
    'title' => 'Parlamentarier',
    'page callback' => 'lobbywatch_parlamentarier_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    );

  $items['parlamentarier/%'] = array(
    'title' => 'Parlamentarier',
    'page callback' => 'lobbywatch_parlamentarier_id',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    );

  $items['organisation'] = array(
    'title' => 'Organisationen',
    'page callback' => 'lobbywatch_organisation_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    );

  $items['organisation/%'] = array(
    'title' => 'Organisation',
    'page callback' => 'lobbywatch_organisation_id',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * TODO
 */
function lobbywatch_parlamentarier_list() {
  $markup = t('<p>Liste der Parlamentarier</p>');
  $markup .= '<ul>';

  // Use the database we set up earlier
  // Ref: https://drupal.org/node/18429
  db_set_active('lobbywatch');

  $result = db_query("SELECT * FROM v_parlamentarier parlamentarier WHERE parlamentarier.im_rat_bis IS NULL ORDER BY parlamentarier.anzeige_name");

  while ($record = $result->fetchAssoc()) {
    $markup .= '<li><a href="/parlamentarier/' . $record['id'] . '">' . $record['anzeige_name'] . '</a>';
  }

  $markup .= '</ul>';

  // Go back to the default database,
  // otherwise Drupal will not be able to access it's own data later on.
  db_set_active();

  $build = array();
  $build['terms'] = array(
    '#weight' => -5,
    '#prefix' => '<div class="lobbywatch">',
    '#markup' => $markup,
    '#suffix' => '</div>',
    );

  return $build;
}

function lobbywatch_parlamentarier_id($id) {

//   dpm($id, 'id');

  $markup = t('<p>Parlamentarier</p>');

  // Use the database we set up earlier
  // Ref: https://drupal.org/node/18429
  db_set_active('lobbywatch');

  $sql = "SELECT parlamentarier.id, parlamentarier.anzeige_name as parlamentarier_name, parlamentarier.email,
  GROUP_CONCAT(DISTINCT
  CONCAT('<li>', organisation.anzeige_name, IF(organisation.rechtsform IS NULL OR TRIM(organisation.rechtsform) = '', '', CONCAT(', ', organisation.rechtsform)), IF(organisation.ort IS NULL OR TRIM(organisation.ort) = '', '', CONCAT(', ', organisation.ort)), ', ', interessenbindung.art, ', ', interessenbindung.beschreibung)
  ORDER BY organisation.anzeige_name
  SEPARATOR ' '
  ) interessenbindungen,
  GROUP_CONCAT(DISTINCT
  CONCAT('<li>', zutrittsberechtigung.name, ', ', zutrittsberechtigung.funktion)
  ORDER BY zutrittsberechtigung.name
  SEPARATOR ' '
  ) zutrittsberechtigungen,
  GROUP_CONCAT(DISTINCT
  CONCAT('<li>', zutrittsberechtigung.name, ', ', zutrittsberechtigung.funktion,
  IF (organisation2.id IS NOT NULL,
  CONCAT(', ',
  organisation2.anzeige_name
  , IF(organisation2.rechtsform IS NULL OR TRIM(organisation2.rechtsform) = '', '', CONCAT(', ', organisation2.rechtsform)), IF(organisation2.ort IS NULL OR TRIM(organisation2.ort) = '', '', CONCAT(', ', organisation2.ort)), ', '
  , IFNULL(mandat.art, ''), ', ', IFNULL(mandat.beschreibung, '')
  ),
  '')
  )
  ORDER BY zutrittsberechtigung.name, organisation2.anzeige_name
  SEPARATOR ' '
  ) mandate,
  CONCAT(
    CASE parlamentarier.geschlecht
    WHEN 'M' THEN CONCAT('<p>Sehr geehrter Herr ', parlamentarier.nachname, '</p>')
    WHEN 'F' THEN CONCAT('<p>Sehr geehrte Frau ', parlamentarier.nachname, '</p>')
    ELSE CONCAT('<p>Sehr geehrte(r) Herr/Frau ', parlamentarier.nachname, '</p>')
    END,
    '<p>[Einleitung]</p>',
    '<p>Ihre <b>Interessenbindungen</b>:</p>',
    '<ul>',
    GROUP_CONCAT(DISTINCT
    CONCAT('<li>', organisation.anzeige_name, IF(organisation.rechtsform IS NULL OR TRIM(organisation.rechtsform) = '', '', CONCAT(', ', organisation.rechtsform)), IF(organisation.ort IS NULL OR TRIM(organisation.ort) = '', '', CONCAT(', ', organisation.ort)), ', ', interessenbindung.art, ', ', interessenbindung.beschreibung)
    ORDER BY organisation.anzeige_name
    SEPARATOR ' '
    ),
    '</ul>',
    '<p>Ihre <b>Gäste</b>:</p>',
    '<ul>',
    GROUP_CONCAT(DISTINCT
    CONCAT('<li>', zutrittsberechtigung.name, ', ', zutrittsberechtigung.funktion)
    ORDER BY zutrittsberechtigung.name
    SEPARATOR ' '
    ),
    '</ul>',
    '<p><b>Mandate</b> der Gäste:</p>',
    '<ul>',
    GROUP_CONCAT(DISTINCT
    CONCAT('<li>', zutrittsberechtigung.name, ', ', zutrittsberechtigung.funktion,
    IF (organisation2.id IS NOT NULL,
    CONCAT(', ',
    organisation2.anzeige_name
    , IF(organisation2.rechtsform IS NULL OR TRIM(organisation2.rechtsform) = '', '', CONCAT(', ', organisation2.rechtsform)), IF(organisation2.ort IS NULL OR TRIM(organisation2.ort) = '', '', CONCAT(', ', organisation2.ort)), ', '
    , IFNULL(mandat.art, ''), ', ', IFNULL(mandat.beschreibung, '')
    ),
    '')
    )
    ORDER BY zutrittsberechtigung.name, organisation2.anzeige_name
    SEPARATOR ' '
    ),
    '</ul>',
    '<p>Freundliche Grüsse<br></p>'
    ) email_text_html
    FROM v_parlamentarier parlamentarier
    LEFT JOIN v_interessenbindung interessenbindung
    ON interessenbindung.parlamentarier_id = parlamentarier.id
    LEFT JOIN v_organisation organisation
    ON interessenbindung.organisation_id = organisation.id
    LEFT JOIN v_zutrittsberechtigung zutrittsberechtigung
    ON zutrittsberechtigung.parlamentarier_id = parlamentarier.id
    LEFT JOIN v_mandat mandat
    ON mandat.zutrittsberechtigung_id = zutrittsberechtigung.id
    LEFT JOIN v_organisation organisation2
    ON mandat.organisation_id = organisation2.id
    WHERE
    parlamentarier.im_rat_bis IS NULL
    AND interessenbindung.bis IS NULL
    AND zutrittsberechtigung.bis IS NULL
    AND mandat.bis IS NULL
    AND parlamentarier.id=:id
    GROUP BY parlamentarier.id";

  $result = db_query($sql, array(':id' => $id));

//     dpm($result, 'result');

    $record = $result->fetchAssoc();

    dpm($record, '$record');

    // Go back to the default database,
    // otherwise Drupal will not be able to access it's own data later on.
    db_set_active();

    $markup .= '<h2>' . $record["parlamentarier_name"] . '</h2>' .
    '<h4>Interessenbindungen</h4><ul>' . $record['interessenbindungen'] . '</ul>' .
    '<h4>Gaeste</h4><ul>' . $record['zutrittsberechtigungen'] . '</ul>' .
    '<h4>Mandate</h4><ul>' . $record['mandate'] . '</ul>';

  $build = array();
  $build['terms'] = array(
    '#weight' => -5,
    '#prefix' => '<div class="lobbywatch">',
    '#markup' => $markup,
    '#suffix' => '</div>',
    );

    return $build;
}
