<?php

/**
 * Implements hook_menu().
 */
function lobbywatch_data_menu() {
  $items = array();

  foreach (Constants::$workflow_tables as $key => $value) {
    $items["data/interface/v1/json/table/$key/flat/id/%"] = array(
      'page callback' => '_lobbywatch_data_table_flat_id',
      'page arguments' => array($key, 8),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
    );

    $items["data/interface/v1/json/table/$key/flat/all"] = array(
      'page callback' => '_lobbywatch_data_table_flat_list',
      'page arguments' => array($key),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
    );
  }

  return $items;
}

/**
* Implements hook_permission().
*/
function lobbywatch_data_permission() {
  return array(
    'access lobbywatch data general content' => array(
      'title' => t('Access general content of the lobbywatch data module'),
    ),
    'access lobbywatch data unpublished content' => array(
      'title' => t('Access unpublished (nicht freigegeben) content of the lobbywatch data module'),
    ),
    'access lobbywatch data confidential content' => array(
      'title' => t('Access unpublished (nicht freigegeben) content of the lobbywatch data module'),
    ),
  );
}

function lobbywatch_data_init() {
}
