<?php

/**
 * Implements hook_menu().
 */
function lobbywatch_data_menu() {
  $items = array();

  foreach (Constants::$workflow_tables as $key => $value) {
    $items["data2/interface/v1/json/table/$key/flat/id/%"] = array(
      'page callback' => '_lobbywatch_data_table_flat_id',
      'page arguments' => array($key, 8, true),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
    );

    $items["data2/interface/v1/json/table/$key/flat/list"] = array(
      'page callback' => '_lobbywatch_data_table_flat_list',
      'page arguments' => array($key, '1', true),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
    );

    $items["data2/interface/v1/json/table/$key/flat/list/%"] = array(
      'page callback' => '_lobbywatch_data_table_flat_list_search',
      'page arguments' => array($key, 8, true),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
    );
  }

  foreach (Constants::getAllEnrichedRelations() as $key => $value) {
    $items["data2/interface/v1/json/relation/$key/flat/list"] = array(
      'page callback' => '_lobbywatch_data_relation_flat_list',
      'page arguments' => array($key, '1', true),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
    );
  }

  $items["data2/interface/v1/json/table/zutrittsberechtigung/aggregated/id/%"] = array(
      'page callback' => '_lobbywatch_data_table_zutrittsberechtigte_aggregated_id',
      'page arguments' => array(8, true),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
  );

  $items["data2/interface/v1/json/table/parlamentarier/aggregated/id/%"] = array(
      'page callback' => '_lobbywatch_data_table_parlamentarier_aggregated_id',
      'page arguments' => array(8, true),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
  );

  $items["data2/interface/v1/json/table/organisation/aggregated/id/%"] = array(
      'page callback' => '_lobbywatch_data_table_organisation_aggregated_id',
      'page arguments' => array(8, true),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
  );

  $items["data2/interface/v1/json/query/parlament-partei/aggregated/list"] = array(
      'page callback' => '_lobbywatch_data_query_parlament_partei_aggregated_list',
      'page arguments' => array('1', true),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
  );

  // TODO error message in case of wrong names
  $items["data2/interface/v1/json/%/%"] = array(
      'page callback' => '_lobbywatch_data_not_found',
      'page arguments' => array(4, 5, true),
      'access arguments' => array('access lobbywatch data general content'),
      'type' => MENU_CALLBACK,
      'file' => 'lobbywatch_data.interface.inc',
  );

//   $items["data/interface/v1/json/table/parlamentarier/aggregated/all"] = array(
//       'page callback' => '_lobbywatch_data_table_parlamentarier_aggregated_list',
//       'page arguments' => array(),
//       'access arguments' => array('access lobbywatch data general content'),
//       'type' => MENU_CALLBACK,
//       'file' => 'lobbywatch_data.interface.inc',
//   );

  return $items;
}

/**
 * Implements hook_js().
 */
function lobbywatch_data_js() {
  return lobbywatch_data_data();
}

/**
 * Implements hook_js().
 */
function lobbywatch_data_data() {
  $items = array();

//   module_load_include('module', 'lobbywatch');

    $items["v1"] = array(
      'callback' => '_lobbywatch_data_router',
      'page arguments' => array(0, 1, 2, 3, 4, 5, 6, false),
      'access arguments' => array('access lobbywatch data general content'),
      'file' => 'lobbywatch_data.interface.inc',
      'dependencies' => array('lobbywatch', 'user'),
      'skip_hook_init' => TRUE,
    );

    return $items;
}

/**
* Implements hook_permission().
*/
function lobbywatch_data_permission() {
  return array(
    'access lobbywatch data general content' => array(
      'title' => t('Access general content of the lobbywatch DB data'),
    ),
    'access lobbywatch data unpublished content' => array(
      'title' => t('Access unpublished (nicht freigegeben) content of the lobbywatch DB data'),
    ),
    'access lobbywatch data confidential content' => array(
      'title' => t('Access confidential (internal) content of the lobbywatch DB data'),
    ),
  );
}

function lobbywatch_data_init() {
}
