<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite4f783595287d4ec0575a352da15066e
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Picqer\\Barcode\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Picqer\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/picqer/php-barcode-generator/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite4f783595287d4ec0575a352da15066e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite4f783595287d4ec0575a352da15066e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite4f783595287d4ec0575a352da15066e::$classMap;

        }, null, ClassLoader::class);
    }
}
