equivalent_functions = [("Persönlicher Mitarbeiter", "Collaborateur(rice) personnel(le)"),
                        ("Persönlicher Mitarbeiter",
                            "Persönliche/r Mitarbeiter/in"),
                        ("Persönliche Mitarbeiterin",
                            "Persönliche/r Mitarbeiter/in"),
                        ("Collaborateur personel",
                            "Collaborateur(rice) personnel(le)"),
                        ("Collaboratrice personale",
                            "Collaboratore/trice personale"),
                        ("Collaboratrice personnelle",
                            "Collaborateur(rice) personnel(le)"),
                        ("Persönliche Mitarbeiterin",
                            "Collaborateur(rice) personnel(le)"),
                        ("Persönliche Mitarbeiterin",
                            "Collaboratore/trice personale"),
                        ("Gast", "Invité(e)"),
                        ("Persönlicher Mitarbeiter", "Collaborateur(rice) personnel(le)")]

president_mapping = {'Co-Präsidenten': ('praesident', ('Co-Präsident', 'Co-Präsidentin'), ('Coprésident', 'Coprésidente')),
                     'Co-Präsident': ('praesident', ('Co-Präsident', 'Co-Präsidentin'), ('Coprésident', 'Coprésidente')),
                     'Präsident': ('praesident', ('Präsident', 'Präsidentin'), ('Président', 'Présidente')),
                     'PräsidentInnen': ('praesident', ('Präsident', 'Präsidentin'), ('Président', 'Présidente')),
                     'Vizepräsidentin': ('vizepraesident', ('Vizepräsident', 'Vizepräsidentin'), ('Vice-président', 'Vice-présidente')),
                     'Vizepräsident': ('vizepraesident', ('Vizepräsident', 'Vizepräsidentin'), ('Vice-président', 'Vice-présidente')),
                     'Vize-Präsident': ('vizepraesident', ('Vize-Präsident', 'Vize-Präsidentin'), ('Vice-président', 'Vice-présidente')),
                     'Präsidentin': ('praesident', ('Präsident', 'Präsidentin'), ('Président', 'Présidente')),
                     'Präsidium': ('praesident', ('Präsidium', 'Präsidium'), ('Président', 'Présidente')),
                     'Co-Präsidium': ('praesident', ('Co-Präsidium', 'Co-Präsidium'), ('Coprésident', 'Coprésidente')),
                     'Co-Präsidentin': ('praesident', ('Co-Präsident', 'Co-Präsidentin'), ('Coprésident', 'Coprésidente')),
                     'Präsident/in': ('praesident', ('Präsident', 'Präsidentin'), ('Président', 'Présidente')),
                     'Co-PräsidentInnen': ('praesident', ('Co-Präsident', 'Co-Präsidentin'), ('Coprésident', 'Coprésidente')),
                     'Co-': ('praesident', ('Co-Präsident', 'Co-Präsidentin'), ('Coprésident', 'Coprésidente')),
                     }
