equivalent_functions = [("Persönlicher Mitarbeiter", "Collaborateur(rice) personnel(le)"),
                        ("Persönlicher Mitarbeiter",
                            "Persönliche/r Mitarbeiter/in"),
                        ("Persönliche Mitarbeiterin",
                            "Persönliche/r Mitarbeiter/in"),
                        ("Collaborateur personel",
                            "Collaborateur(rice) personnel(le)"),
                        ("Collaboratrice personale",
                            "Collaboratore/trice personale"),
                        ("Collaboratrice personnelle",
                            "Collaborateur(rice) personnel(le)"),
                        ("Persönliche Mitarbeiterin",
                            "Collaborateur(rice) personnel(le)"),
                        ("Persönliche Mitarbeiterin",
                            "Collaboratore/trice personale"),
                        ("Gast", "Invité(e)"),
                        ("Persönlicher Mitarbeiter", "Collaborateur(rice) personnel(le)")]

president_mapping = {'Co-Präsidenten': ('Co-Präsident', 'Co-Präsidentin', 'praesident'),
                     'Co-Präsident': ('Co-Präsident', 'Co-Präsidentin', 'praesident'),
                     'Präsident': ('Präsident', 'Präsidentin', 'praesident'),
                     'PräsidentInnen': ('Präsident', 'Präsidentin', 'praesident'),
                     'Vizepräsidentin': ('Vizepräsident', 'Vizepräsidentin','vizepraesident'),
                     'Vizepräsident': ('Vizepräsident', 'Vizepräsidentin','vizepraesident'),
                     'Vize-Präsident': ('Vize-Präsident', 'Vize-Präsidentin','vizepraesident'),
                     'Präsidentin': ('Präsident', 'Präsidentin', 'praesident'),
                     'Präsidium': ('Präsidium', 'Präsidium', 'praesident'),
                     'Co-Präsidium': ('Co-Präsidium', 'Co-Präsidium', 'praesident'),
                     'Co-Präsidentin': ('Co-Präsident', 'Co-Präsidentin', 'praesident'),
                     'Präsident/in': ('Präsident', 'Präsidentin', 'praesident'),
                     'Co-PräsidentInnen': ('Co-Präsident', 'Co-Präsidentin', 'praesident'),
                     'Co-': ('Co-Präsident', 'Co-Präsidentin', 'praesident')
                     }
