import csv
import json
import os
import re
from argparse import ArgumentParser
from datetime import datetime
from shutil import copyfile
from subprocess import call
from typing import Union

import pdf_helpers
from utils import clean_str, clean_whitespace

TITLE_CSV = "zb_title.csv"
DATA_CSV = "zb_data.csv"
CONTENT_PDF = "zb_file-content.pdf"

def split_names(names):
    return names.replace('"', "").replace(".", "").split(" ")


class Entity:
    # remove invalid characters from cell entries
    def clean_string(self, s):
        return clean_str(s).replace("\n", " ").replace(' - ', '-')


# represents a member of parliament
class MemberOfParliament(Entity):
    def __init__(self, s):
        # members of parliament are formatted as
        # "[names]"
        # this entire text is passed into the constructor
        full_name = self.clean_string(s)
        self.names = split_names(full_name)
        self.names = self.fix_names(self.names)

    def fix_names(self, names):
        if names == ['Docourt', 'Ducommun-', 'dit-Boudry', 'Martine']:
            return ['Docourt', 'Martine']
        elif names == ['Bally', 'Frehner', 'Maja']:
            return ['Bally', 'Maya']
        elif names == ['Roth', 'Pasquier', 'Marie-', 'France']:
            return ['Roth Pasquier', 'Marie-France']
        else:
            return names

    # <faction>/<canton>
    def set_faction_and_canton(self, s):
        faction_and_canton = s.split("/")
        self.faction = faction_and_canton[0].strip()
        # Hack for wrong faction
        if self.faction == 'los' and self.names == ['Poggia', 'Mauro']:
            self.faction = 'V'
        self.canton = faction_and_canton[1].strip()

        # TODO remove
        # # The FDP can show up as "FDP-Liberale",
        # # so we need to get only the part before the dash
        # faction_split = faction.split("-")
        # if len(faction_split) == 1:
        #     self.faction = faction
        # else:
        #     self.faction = faction_split[0]
        # Partei mapping al -> ALG (hack)
        # if self.faction == 'Al':
        #     self.faction = 'ALG'

    def append_names(self, s):
        names = self.clean_string(s)
        self.names += split_names(names)
        self.names = self.fix_names(self.names)

# represents a guest of a member of parliament
class Guest(Entity):
    def __init__(self, name_raw, function):
        name = self.clean_string(name_raw)
        name = self.fix_name_typos(name)
        self.names = split_names(name)
        self.function = self.clean_string(function)
        self.gender = 'F' if "Frau" in name_raw or "Madame" in name_raw else "M"

    # namemapping fixes, a hack
    def fix_name_typos(self, name):
        # () around calls for multi line writing, insteaf of "\" at EOL
        # https://stackoverflow.com/questions/4768941/how-to-break-a-line-of-chained-methods-in-python
        return (name
        .replace("Schürch Florence", "Schurch Florence")
        .replace("Grunder Michael", "Grunder Michel")
        .replace("Voegeli Tobias", "Vögeli Tobias")
        .replace("Durig Terence", "Durig Térence")
        .replace("Giovanoli Remco", "Giovanoli Remco André")
        .replace("Rosenkrantz Linda", "Rosenkranz Linda")
        )

    def remove_title(self, name):
        return re.sub(r'(Herr|Frau|Monsieur|Madame|Dr.|Signora?)\s+', ' ', name).strip()

    def append_function(self, s):
        self.function += " " + self.clean_string(s)

    def append_names(self, s):
        name = self.clean_string(s)
        name = self.fix_name_typos(name)
        self.names += split_names(name)

# Parsing rules for the tabula-extracted CSV:
#
# Row types (decided by row[0]):
#   empty      → new guest (if row[1] has 2+ words) or continuation of last guest
#   has "/"    → faction/canton; same continuation logic as empty rows; sets new_member=True
#   non-empty, no "/" + new_member=True  → first line of a new member of parliament
#   non-empty, no "/" + new_member=False → member name continuation
#
# Name column (row[1]) disambiguation:
#   empty rows: 2+ words → new guest; 1 word → name continuation
#   faction/canton rows: 2+ words AND non-empty function → new guest; otherwise → name continuation
#     (a multi-word first name like "Monika Ruth" can appear without a function and is a continuation)
#
# Member-name-continuation rows may also carry row[1] (guest name continuation)
# and row[2] (function continuation) for the current last guest.

def _is_complete_name(name: str) -> bool:
    return len(name.split()) >= 2

def _apply_continuation(current_guest, row1: str, row2: str) -> None:
    if current_guest is not None:
        if not is_empty(row1):
            current_guest.append_names(row1)
        if not is_empty(row2):
            current_guest.append_function(row2)

# read the csv generated by tabula and get rid of empty rows and headers
def read_guests(filename: str) -> list[dict[str, str]]:
    guests: dict[MemberOfParliament, list[Guest]] = {}
    current_member: MemberOfParliament | None = None
    current_guest: Guest | None = None
    new_member: bool = True

    for row in csv.reader(open(filename, encoding="utf-8")):
        if is_header(row) or is_empty_row(row) or is_page_number(row):
            continue

        # SR CSV sometimes produces an empty 4th column — crash if it ever has actual content
        if len(row) > 3 and row[3] != '':
            raise Exception("Too long line: {}".format(row))

        row1 = row[1] if len(row) > 1 else ''
        row2 = row[2] if len(row) > 2 else ''

        if is_empty(row[0]):
            # empty first column: new guest or continuation of last guest
            if not is_empty(row1):
                if _is_complete_name(row1):
                    current_guest = Guest(row1, row2)
                    guests[current_member].append(current_guest)
                else:
                    _apply_continuation(current_guest, row1, row2)
            elif not is_empty(row2) and current_guest is not None:
                current_guest.append_function(row2)

        elif is_faction_and_canton(row[0]):
            current_member.set_faction_and_canton(row[0])
            if not is_empty(row1):
                if _is_complete_name(row1) and not is_empty(row2):
                    current_guest = Guest(row1, row2)
                    guests[current_member].append(current_guest)
                else:
                    _apply_continuation(current_guest, row1, row2)
            elif not is_empty(row2) and current_guest is not None:
                current_guest.append_function(row2)
            new_member = True

        else:
            if new_member:
                # first line of a new member of parliament
                current_member = MemberOfParliament(row[0])
                current_guest = None
                guests[current_member] = []
                new_member = False
                if not is_empty(row1):
                    current_guest = Guest(row1, row2)
                    guests[current_member].append(current_guest)
            else:
                # member name spans multiple rows; row1/row2 may continue the last guest
                current_member.append_names(row[0])
                _apply_continuation(current_guest, row1, row2)

    # print counts for sanity check
    counts: dict[int, int] = {}
    for g_list in guests.values():
        n = len(g_list)
        counts[n] = counts.get(n, 0) + 1
    print("{} members of parliament\n{} guests total".format(
        len(guests), sum(len(g) for g in guests.values())))
    for n in sorted(counts):
        print("  {:>3} members with {} {}".format(counts[n], n, "guest" if n == 1 else "guests"))

    return convert_guests(guests)

# PYTHON <= 3.9 workaround: list[dict[str, str|dict[str, str]]]:
def convert_guests(guests: dict[MemberOfParliament, list[Guest]]) -> list[dict[str, Union[str, dict[str, str]]]]:
    return [{
        "names": member_of_parliament.names,
        "faction": member_of_parliament.faction,
        "canton": member_of_parliament.canton,
        "guests": [{
            "names": guest.names,
            "function": guest.function,
            # "gender": guest.gender
            } for guest in current_guests]
        } for member_of_parliament, current_guests in guests.items()]


# is this table row a header row?
def is_header(row):
    if len(row) < 2:
        return True
    header_words = [
        "Ratsmitglied",
        "Fraktion / Kanton",
        "Partei / Kanton",
        "Membre du Conseil",
        "Parti / Canton",
        "Groupe / Canton",
        "Membro del Consiglio",
        "Partito / Cantone",
        "Gruppo / Cantone"
    ]

    return any(header_word in row_entry
               for header_word in header_words
               for row_entry in row)


# is this table row empty?
def is_empty_row(row):
    return all(len(entry.strip()) == 0 for entry in row)


def is_page_number(row):
    return row[0] == '' and row[1] == '' and (re.match(r'\d+/\d+', row[2]) != None or (len(row) > 3 and re.match(r'\d+/\d+', row[3]) != None))

# is the field empty or contains only whitespace?
def is_empty(s):
    return len(s.strip()) == 0


def is_faction_and_canton(s):
    # members of parliament are formatted as
    # <fraction>/<canton>"
    return "/" in s


# write member of parliament and guests to json file
def write_to_json(guests_data, archive_pdf_name, filename, url, creation_date, modified_date, imported_date, stand_date):
    metadata_data = {
                "metadata": {
                    "archive_pdf_name": archive_pdf_name,
                    "filename": filename,
                    "url": url,
                    "pdf_creation_date": creation_date.isoformat(' '), # , timespec is addedin Python 3.6: 'seconds'
                    "pdf_modified_date": modified_date.isoformat(' '), # , timespec is addedin Python 3.6: 'seconds'
                    "imported_date": imported_date.isoformat(' '), # , timespec is addedin Python 3.6: 'seconds'
                    "stand_date": stand_date.isoformat()
                },
                "data": guests_data
    }
    with open(filename, "wb") as json_file:
        contents = json.dumps(metadata_data, indent=2,
                              separators=(',', ': '),
                              ensure_ascii=False).encode("utf-8")
        json_file.write(contents)

# Get path of this python script
# http://stackoverflow.com/questions/4934806/how-can-i-find-scripts-directory-with-python
def get_script_path():
    return os.path.dirname(os.path.realpath(__file__))

# download a pdf containing the guest lists of members of parlament in a table
# then parse the file into json and save the json files to disk
def scrape_pdf(url: str, local_pdf: str, json_filename: str, suffix: str):
    script_path = get_script_path()
    try:
        raw_pdf_name = url.split("/")[-1]
        import_date = datetime.now().replace(microsecond=0)
        pdf_name = "{}-{}".format(import_date.strftime("%Y-%m-%d"), raw_pdf_name)
        if local_pdf is None:
            print("\ndownloading " + url)
            pdf_helpers.get_pdf_from_admin_ch(url, pdf_name)
        else:
            print("\ncopy local PDF " + local_pdf)
            copyfile(local_pdf, pdf_name)

        print("\nextracting metadata...")
        creation_date, modified_date = pdf_helpers.extract_creation_date(pdf_name)

        tabula_path = script_path + "/tabula-1.0.5-jar-with-dependencies.jar"
        print("parsing title page PDF...")
        cmd = ["java", "-Djava.util.logging.config.file=web_scrapers/logging.properties", "-jar", tabula_path, pdf_name, "-o", TITLE_CSV, "--pages", "1", "-t", "-i"]
        print(" ".join(cmd))
        call(cmd, stderr=None)
        stand_date = pdf_helpers.read_stand(TITLE_CSV)
        print("\nStand: {}".format(stand_date.strftime("%d.%m.%Y")))
        print("PDF creation date: {}".format(creation_date.strftime("%d.%m.%Y")))
        print("PDF modified date: {}\n".format(modified_date.strftime("%d.%m.%Y")))
        archive_pdf_name = "{}-{}".format(stand_date.strftime("%Y-%m-%d"), raw_pdf_name)

        print("removing first page of PDF...")
        call(["qpdf", "--pages", pdf_name, "2-z", "--", pdf_name, CONTENT_PDF])

        print("parsing content PDF...")
        cmd = ["java", "-Djava.util.logging.config.file=web_scrapers/logging.properties", "-jar", tabula_path, CONTENT_PDF, "-o", DATA_CSV, "--pages", "all", "-i"]
        print(" ".join(cmd))
        call(cmd, stderr=None)

        print("cleaning up parsed data...")
        guests = read_guests(DATA_CSV)

        print("writing " + json_filename + "...")
        write_to_json(guests, archive_pdf_name, json_filename, url, creation_date, modified_date, import_date, stand_date)

        if local_pdf is None:
            archive_json_filename = "{}-{}".format(creation_date.strftime("%Y-%m-%d"), json_filename)
            print("archiving PDF " + archive_pdf_name)
            copyfile(pdf_name, script_path + "/archive/{}".format(archive_pdf_name))
            print("archiving JSON ...")
            copyfile(json_filename, script_path + "/archive/{}".format(archive_json_filename))

    finally:
        print("cleaning up...")
        if local_pdf is None:
            os.rename(pdf_name, script_path + "/backup/{}".format(pdf_name))
        else:
            if os.path.isfile(pdf_name): os.remove(pdf_name)
        backup_filename = "{}-{}".format(import_date.strftime("%Y-%m-%d"), json_filename)
        if os.path.isfile(json_filename): copyfile(json_filename, script_path + "/backup/{}".format(backup_filename))
        if os.path.isfile(CONTENT_PDF): os.remove(CONTENT_PDF)
        if os.path.isfile(TITLE_CSV): os.remove(TITLE_CSV)
        if os.path.isfile(DATA_CSV): os.rename(DATA_CSV, "zb_data_{}.csv".format(suffix))

# scrape the nationalrat and ständerat guest lists and write them to
# structured JSON files
def scrape():
    parser = ArgumentParser(description='Scarpe Parlamentarische Gruppen PDF')
    parser.add_argument("local_pdf_NR", metavar="file", nargs='?', help="local PDF file for NR to use", default=None)
    parser.add_argument("local_pdf_SR", metavar="file", nargs='?', help="local PDF file for SR to use", default=None)
    args = parser.parse_args()
    local_pdf_nr = args.local_pdf_NR
    local_pdf_sr = args.local_pdf_SR

    if local_pdf_nr and not local_pdf_sr:
        print('Error: local PDF files must be filled for NR and SR')
        exit(1)

    root = "https://www.parlament.ch/centers/documents/de/"

    #scrape nationalrat
    scrape_pdf(root +
               "zutrittsberechtigte-nr.pdf",
               local_pdf_nr,
               "zutrittsberechtigte-nr.json",
               "nr")

    #scrape ständerat
    scrape_pdf(root +
               "zutrittsberechtigte-sr.pdf",
               local_pdf_sr,
               "zutrittsberechtigte-sr.json",
               "sr")


#main method
if __name__ == "__main__":
    scrape()
